### ISSUE TITLE
[FPCA] Procedure when no specified mean BW and no method to estimate it

### ISSUE THREAD

**Issue by MichaelJStein** [cran/fdapace#1]
Hi,

Regarding the **FPCA** function with sparse data:
Could you please elaborate on the procedure when there is no specified bandwidth value for the smoothed mean function as well as no method to estimate it (e.g. CV). 

I think lines 58-60 of the SetOptions function apply in this case:
```
if(is.null(userBwMu) && methodBwMu == 'Default'){ # bandwidth choice for mean function is using CV or GCV
    userBwMu = 0.05 * diff(range(unlist(t)));   
  } 
```
 
I'm wondering, why is this?

Thank you very much for explaining!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
